import { useEffect, useRef, useState, type ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Compass, ExternalLink, Globe2, LayoutGrid, List, MapPin, Menu, Radio, RefreshCw, Search, SlidersHorizontal, Sparkles, SquareArrowOutUpRight, Timer, TrendingUp, Wifi, X, Zap, BriefcaseBusiness, Activity } from 'lucide-react';
import type { Feed, Job, Overview, Source, Run } from './types';

async function api<T>(path:string,options?:RequestInit):Promise<T> {
  const r=await fetch(path,options);
  const d=await r.json().catch(()=>{throw new Error(`The service could not complete this request (HTTP ${r.status}). Please try again.`);}) as T & {error?:string};
  if(!r.ok) throw new Error(d.error || 'Something went wrong. Please try again.');
  return d;
}
function ago(iso:string|null):string {
  if(!iso) return 'Not checked yet';
  const minutes=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60_000));
  return minutes<1?'Just now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;
}
function localDate(iso:string|null):string {return iso?new Date(iso).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'Not available';}
function pay(job:Job):string {
  if((!job.payMin && !job.payMax) || !job.currency) return 'Pay not listed';
  const fmt=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:job.currency!,maximumFractionDigits:n%1?2:0}).format(n);
  const range=job.payMin&&job.payMax?`${fmt(job.payMin)}–${fmt(job.payMax)}`:job.payMin?`From ${fmt(job.payMin)}`:`Up to ${fmt(job.payMax!)}`;
  return `${range}${job.payPeriod?` / ${job.payPeriod==='hour'?'hr':job.payPeriod}`:''}`;
}
const STATUS:Record<string,{label:string;className:string}>={healthy:{label:'Connected',className:'healthy'},blocked:{label:'Access restricted',className:'blocked'},needs_adapter:{label:'Adapter needed',className:'pending'},error:{label:'Needs attention',className:'blocked'},pending:{label:'Not checked',className:'pending'}};
const BRAND:Record<string,{text:string;color:string;bg:string}>={meta:{text:'∞',color:'#0866ff',bg:'#e8f1fd'},microsoft:{text:'M',color:'#6d5bc6',bg:'#f1ecfa'},airbnb:{text:'A',color:'#e64e63',bg:'#fff0f0'},boeing:{text:'B',color:'#174aa5',bg:'#eef3fb'},jnj:{text:'J&J',color:'#c42625',bg:'#fff0f0'},astrazeneca:{text:'AZ',color:'#a57a17',bg:'#faf5e7'},farmers:{text:'F',color:'#34577e',bg:'#ecf0f6'},johndeere:{text:'JD',color:'#357e35',bg:'#ecf4e8'},nikeinc:{text:'N',color:'#151515',bg:'#f0f0ee'},pinterest:{text:'P',color:'#cb2540',bg:'#fff0f2'},coinbase:{text:'C',color:'#1652f0',bg:'#edf2ff'},abbott:{text:'a',color:'#156898',bg:'#eaf5fc'},solidigm:{text:'S',color:'#64439c',bg:'#f4eefa'}};
function CompanyMark({id,company,size='normal'}:{id:string;company:string;size?:string}) {const b=BRAND[id] || {text:company.split(' ').map(w=>w[0]).slice(0,2).join(''),color:'#436457',bg:'#eef3ef'};return <span className={`company-mark ${size}`} style={{color:b.color,background:b.bg}} aria-hidden="true">{b.text}</span>;}
function Logo(){return <div className="brand"><span className="brand-icon"><svg width="28" height="28" viewBox="0 0 64 64" fill="none"><path d="M17 44 32 14l15 30M24 32h16" stroke="currentColor" strokeWidth="5" strokeLinejoin="round"/><circle cx="45" cy="47" r="5" fill="currentColor"/></svg></span><span>contract<span className="brand-line">atlas<span className="brand-dot">.</span></span></span></div>;}
function useStoredIds(){const [ids,setIds]=useState<string[]>(()=>{try {const v=JSON.parse(localStorage.getItem('atlas-saved')||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}catch{return [];}});return [ids,(id:string)=>setIds(current=>{const next=current.includes(id)?current.filter(x=>x!==id):[...current,id];localStorage.setItem('atlas-saved',JSON.stringify(next));return next;})] as const;}

export default function App(){
  const qc=useQueryClient();
  const searchRef=useRef<HTMLInputElement>(null);
  const [pageView,setPageView]=useState<'explore'|'saved'|'sources'|'activity'>('explore');
  const [saved,toggleSaved]=useStoredIds();
  const [q,setQ]=useState(''),[location,setLocation]=useState(''),[search,setSearch]=useState(''),[searchLocation,setSearchLocation]=useState('');
  const [category,setCategory]=useState(''),[companies,setCompanies]=useState<string[]>([]),[modes,setModes]=useState<string[]>([]),[country,setCountry]=useState(''),[freshness,setFreshness]=useState(''),[onlyPay,setOnlyPay]=useState(false);
  const [sort,setSort]=useState('newest'),[page,setPage]=useState(1),[layout,setLayout]=useState<'grid'|'list'>('grid');
  const [selected,setSelected]=useState<Job|null>(null),[menu,setMenu]=useState(false),[filterOpen,setFilterOpen]=useState(false),[info,setInfo]=useState(false);
  const [refresh,setRefresh]=useState<(Run & {processed?:number})|null>(null),[refreshing,setRefreshing]=useState(false),[notice,setNotice]=useState(''),[sourceQuery,setSourceQuery]=useState(''),[provider,setProvider]=useState('All providers');
  const overview=useQuery({queryKey:['overview'],queryFn:()=>api<Overview>('/api/overview'),refetchInterval:60_000});
  const sources=useQuery({queryKey:['sources'],queryFn:()=>api<Source[]>('/api/sources'),refetchInterval:60_000});
  const params=new URLSearchParams({page:String(page),sort});
  if(search)params.set('q',search);if(searchLocation)params.set('location',searchLocation);if(category)params.set('category',category);if(country)params.set('country',country);if(freshness)params.set('freshness',freshness);if(onlyPay)params.set('pay','yes');companies.forEach(c=>params.append('company',c));modes.forEach(m=>params.append('mode',m));
  if(pageView==='saved') {if(saved.length)saved.forEach(id=>params.append('id',id));else params.append('id','__empty_saved__');}
  const feed=useQuery({queryKey:['jobs',params.toString(),pageView],queryFn:()=>api<Feed>(`/api/jobs?${params}`),enabled:pageView==='explore'||pageView==='saved',placeholderData:previous=>previous,refetchInterval:60_000});
  const access=useQuery({queryKey:['access'],queryFn:()=>api<{canRefresh:boolean}>('/api/access')});
  const runs=useQuery({queryKey:['runs'],queryFn:()=>api<(Run & {processed:number})[]>('/api/runs'),enabled:pageView==='activity',refetchInterval:refreshing?3000:60_000});
  useEffect(()=>{setPage(1);},[search,searchLocation,category,companies,modes,country,freshness,onlyPay,sort,pageView]);
  useEffect(()=>{const focusSearch=(event:KeyboardEvent)=>{const tag=(event.target as HTMLElement)?.tagName;if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(tag)){event.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',focusSearch);return()=>window.removeEventListener('keydown',focusSearch);},[]);
  useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timeout);},[notice]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('job');if(id)api<Job>(`/api/jobs/${encodeURIComponent(id)}`).then(setSelected).catch(()=>{});},[]);
  const stats=overview.data;
  const allSources=sources.data || [];
  const incompleteCoverage=!!stats && stats.completeSources<stats.sourceCount;
  const lastChecked=allSources.map(s=>s.lastCheckedAt).filter((x):x is string=>!!x).sort().at(-1)||null;
  const activeFilters=companies.length+modes.length+Number(!!category)+Number(!!country)+Number(!!freshness)+Number(onlyPay)+Number(!!search)+Number(!!searchLocation);
  const clear=()=>{setCompanies([]);setModes([]);setCategory('');setCountry('');setFreshness('');setOnlyPay(false);setSearch('');setQ('');setSearchLocation('');setLocation('');};
  const changeView=(view:typeof pageView)=>{setPageView(view);setMenu(false);clear();};
  async function refreshRoles(){
    if(refreshing)return;
    setRefreshing(true);
    try {
      if(!access.data?.canRefresh) {
        await qc.invalidateQueries();
        setNotice('Feed reloaded. Check source timestamps for collection freshness.');
        return;
      }
      let r=await api<Run & {processed:number}>('/api/refresh',{method:'POST'});setRefresh(r);
      while(r.status==='running') {const previous=r.processed;r=await api<Run & {processed:number}>(`/api/refresh/${r.id}/step`,{method:'POST'});setRefresh(r);qc.invalidateQueries({queryKey:['overview']});qc.invalidateQueries({queryKey:['sources']});if(r.status==='running'&&r.processed===previous)await new Promise(resolve=>setTimeout(resolve,1000));}
      setNotice(`Refresh complete. ${r.newCount} new ${r.newCount===1?'role':'roles'} found. ${r.successCount} of ${r.sourceCount} sources connected.`);
      await qc.invalidateQueries({queryKey:['jobs']});await qc.invalidateQueries({queryKey:['runs']});
    } catch(e){setNotice(e instanceof Error?e.message:'Refresh interrupted. You can resume with Refresh roles.');}
    finally{setRefreshing(false);}
  }
  function openJob(job:Job){setSelected(job);const u=new URL(window.location.href);u.searchParams.set('job',job.id);history.replaceState(null,'',u);}
  function closeJob(){setSelected(null);const u=new URL(window.location.href);u.searchParams.delete('job');history.replaceState(null,'',u);}
  function save(job:Job){toggleSaved(job.id);setNotice(saved.includes(job.id)?'Role removed from your saved list.':'Role saved. Find it in Saved roles.');}
  const chips=['','Engineering & IT','Data & Analytics','Design & Creative','Product & Operations'];

  return <div className="app-shell">
    {menu&&<div className="mobile-backdrop" onClick={()=>setMenu(false)}/>}
    <aside className={`sidebar ${menu?'open':''}`}>
      <Logo/>
      <div className="workspace-label">YOUR OPPORTUNITY SPACE</div>
      <nav aria-label="Main navigation">
        <button className={pageView==='explore'?'nav-item active':'nav-item'} onClick={()=>changeView('explore')}><Compass size={19}/><span>Explore roles</span><span className="nav-pip"/></button>
        <button className={pageView==='saved'?'nav-item active':'nav-item'} onClick={()=>changeView('saved')}><Bookmark size={18}/><span>Saved roles</span>{saved.length>0&&<span className="nav-count">{saved.length}</span>}</button>
        <div className="nav-divider"/>
        <button className={pageView==='sources'?'nav-item active':'nav-item'} onClick={()=>changeView('sources')}><Globe2 size={18}/><span>Source directory</span><ArrowUpRight size={14}/></button>
        <button className={pageView==='activity'?'nav-item active':'nav-item'} onClick={()=>changeView('activity')}><Activity size={18}/><span>Refresh activity</span></button>
      </nav>
      <div className="sidebar-bottom">
        <div className="sync-card"><span className="sync-symbol"><Radio size={19}/></span><strong>A fresh perspective.</strong><p>{stats?.scheduleEnabled?'Source checks are scheduled every two hours. Check times can vary.':'Browse verified roles and check source health in one place.'}</p><div className="sync-mini"><span className={stats?.scheduleEnabled?'live-dot':'neutral-dot'}/>{stats?.scheduleEnabled?'Two-hour checks scheduled':'Latest published snapshot'}</div></div>
        <button className="help-link" onClick={()=>setInfo(true)}><CircleHelp size={17}/>How Contract Atlas works<ArrowUpRight size={14}/></button>
        <div className="profile"><span className="avatar">RD</span><div><strong>Rohit’s workspace</strong><small>Your personal job radar</small></div></div>
      </div>
    </aside>
    <main>
      <header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setMenu(!menu)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={13}/><strong>{pageView==='explore'?'Explore roles':pageView==='saved'?'Saved roles':pageView==='sources'?'Source directory':'Refresh activity'}</strong></div><div className="topbar-actions"><span className="freshness-indicator"><span className={stats?.scheduleEnabled?'live-dot':'neutral-dot'}/>{stats?.scheduleEnabled?'Two-hour checks scheduled':'Verified source data'}</span><button className="refresh-button" disabled={refreshing} onClick={refreshRoles}><RefreshCw size={15} className={refreshing?'spin':''}/>{refreshing?(access.data?.canRefresh?`Checking ${refresh?.processed || 0}/${stats?.sourceCount || 59}`:'Loading feed…'):(access.data?.canRefresh?'Refresh roles':'Reload feed')}</button></div></header>
      <div className="main-content">
        {(pageView==='explore'||pageView==='saved')&&<>
          <section className="hero">
            <div><div className="eyebrow"><span className="eyebrow-line"/>{pageView==='saved'?'YOUR NEXT CHAPTER':'GOOD WORK. MORE FREEDOM.'}</div><h1>{pageView==='saved'?<>Keep your next<br/><em>move in sight.</em></>:<>Your next chapter.<br/><em>On your terms.</em></>}</h1><p>{pageView==='saved'?'A little shortlist for your big next move. Your saved roles stay here on this device.':'Contract opportunities from company talent communities. One place to find the work that fits your life.'}</p><div className="hero-note"><span className="tiny-check"><Check size={11}/></span>Direct links to original listings <span className="dot-separator">·</span> No noise. Just possibilities.</div></div>
            <div className="hero-art" aria-hidden="true"><svg className="orbit" viewBox="0 0 330 180"><ellipse cx="165" cy="98" rx="134" ry="63" fill="none" stroke="#cad8cd" strokeDasharray="3 6" transform="rotate(-20 165 98)"/><path d="M236 31l12-2-3 12" fill="none" stroke="#5d826a" strokeWidth="2"/><path d="M66 143l-11 3 1-12" fill="none" stroke="#5d826a" strokeWidth="2"/></svg><div className="art-card back-card"><Globe2 size={18}/><span>A world of opportunity</span><span className="card-dots">•••</span></div><div className="art-card front-card"><span className="art-briefcase"><BriefcaseBusiness size={22}/></span><div><strong>Make your next move.</strong><small>Great companies. Flexible chapters.</small></div><span className="art-arrow"><ArrowUpRight size={19}/></span></div><div className="art-label"><span className="live-dot"/>{stats?.sourceCount || 59} company communities, one feed</div><Sparkles className="art-sparkle" size={25}/></div>
          </section>
          <section className="metric-strip" aria-label="Job feed statistics"><Metric icon={<BriefcaseBusiness size={20}/>} value={stats?.totalJobs} label="Open contract roles" sub="From connected sources"/><Metric icon={<Sparkles size={20}/>} value={stats?.newToday} label="Posted in the last 24h" sub="Based on source posting dates"/><Metric icon={<Globe2 size={20}/>} value={stats?.healthySources} label="Readable sources" sub={`${stats?.completeSources ?? 0} of ${stats?.sourceCount || 59} fully retrieved`}/><div className="metric metric-sync"><span className="metric-icon muted"><Clock3 size={20}/></span><div><strong className="sync-time">{ago(lastChecked)}</strong><span>Last source check</span><small>{stats?.nextRefreshAt?`Next check at ${new Date(stats.nextRefreshAt).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}`:'Refresh any time'}</small></div></div></section>
          {incompleteCoverage&&<div className="coverage-notice" role="status"><Globe2 size={18}/><div><strong>Coverage is incomplete.</strong><p>{stats.completeSources} of {stats.sourceCount} feeds fully retrieved; {stats.partialSources} additional feeds have partial results. A missing result may still be available on its original portal.</p></div><button onClick={()=>changeView('sources')}>Review sources<ArrowUpRight size={15}/></button></div>}
          <form className="search-bar" onSubmit={e=>{e.preventDefault();setSearch(q);setSearchLocation(location);setPage(1);}}><label className="keyword-input"><Search size={20}/><input ref={searchRef} aria-keyshortcuts="/" value={q} onChange={e=>setQ(e.target.value)} placeholder="Job title, skill, or company" aria-label="Search job title, skill, or company"/><kbd>/</kbd></label><label className="location-input"><MapPin size={19}/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="City, state, or country" aria-label="Search location"/></label><button className="search-button" type="submit">Find my next role<ArrowRight size={17}/></button></form>
          <div className="category-chips" aria-label="Role category"><span>Explore by</span>{chips.map(c=><button key={c} className={category===c?'chip selected':'chip'} onClick={()=>setCategory(c)}>{c||'All roles'}{category===c&&<Check size={13}/>}</button>)}<select value={chips.includes(category)?'':category} onChange={e=>setCategory(e.target.value)} aria-label="More role categories"><option value="">More categories</option>{(feed.data?.facets.categories||[]).filter(c=>!chips.includes(c.name)).map(c=><option key={c.name}>{c.name}</option>)}</select></div>
          <div className="feed-layout">
            <aside className={`filters ${filterOpen?'filters-open':''}`}><div className="filter-heading"><h2>Filters{activeFilters>0&&<span>{activeFilters}</span>}</h2><button onClick={clear}>Reset</button><button className="filter-close icon-button" aria-label="Close filters" onClick={()=>setFilterOpen(false)}><X size={18}/></button></div><FilterSection title="Work arrangement"><div className="filter-options">{['Remote','Hybrid','On-site','Unspecified'].map(m=><CheckFilter key={m} label={m==='Unspecified'?'Not specified':m} checked={modes.includes(m)} onChange={()=>setModes(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m])}/>)}</div></FilterSection><FilterSection title="Posted"><div className="posted-options">{[['','Any time'],['24h','Last 24 hours'],['7d','Last 7 days'],['30d','Last 30 days']].map(([v,label])=><label key={v}><input type="radio" name="freshness" value={v} checked={freshness===v} onChange={()=>setFreshness(v)}/>{label}{v==='24h'&&<span className="new-tag">NEW</span>}</label>)}</div></FilterSection><FilterSection title="Company"><div className="filter-options company-options">{(feed.data?.facets.companies || []).map(c=><CheckFilter key={c.name} label={c.name} count={c.count} checked={companies.includes(c.name)} onChange={()=>setCompanies(v=>v.includes(c.name)?v.filter(x=>x!==c.name):[...v,c.name])}/>)}</div>{!feed.data?.facets.companies.length&&<small>No connected listings yet.</small>}</FilterSection><FilterSection title="Country"><select className="filter-select" value={country} onChange={e=>setCountry(e.target.value)} aria-label="Filter by country"><option value="">All countries</option>{feed.data?.facets.countries.map(c=><option key={c}>{c}</option>)}</select></FilterSection><FilterSection title="Compensation"><CheckFilter label="Only roles with listed pay" checked={onlyPay} onChange={()=>setOnlyPay(v=>!v)}/></FilterSection><div className="source-callout"><Globe2 size={19}/><strong>Go straight to the source.</strong><p>Every role links to the original company talent community.</p><button onClick={()=>changeView('sources')}>Explore our sources<ArrowUpRight size={15}/></button></div></aside>
            <section className="results"><div className="results-toolbar"><div><h2>{pageView==='saved'?'Your saved roles':'Your next opportunity'}<span>{feed.data?.total || 0}</span></h2><p>{pageView==='saved'?'A shortlist worth coming back to.':activeFilters?'A little closer to the right fit.':'A fresh start is closer than you think.'}</p></div><div className="result-controls"><button className="mobile-filter" onClick={()=>setFilterOpen(!filterOpen)}><SlidersHorizontal size={16}/>Filters</button><label className="sort-select">Sort by <select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort roles"><option value="newest">Newest posted</option><option value="discovered">Recently discovered</option><option value="company">Company name</option><option value="pay">Highest USD / hr</option></select><ChevronDown size={13}/></label><div className="layout-switch"><button aria-label="Grid view" aria-pressed={layout==='grid'} className={layout==='grid'?'active':''} onClick={()=>setLayout('grid')}><LayoutGrid size={16}/></button><button aria-label="List view" aria-pressed={layout==='list'} className={layout==='list'?'active':''} onClick={()=>setLayout('list')}><List size={17}/></button></div></div></div>
            {activeFilters>0&&<div className="active-filters">{search&&<button onClick={()=>{setSearch('');setQ('');}}>{search}<X size={12}/></button>}{category&&<button onClick={()=>setCategory('')}>{category}<X size={12}/></button>}{modes.map(m=><button key={m} onClick={()=>setModes(v=>v.filter(x=>x!==m))}>{m}<X size={12}/></button>)}<button className="clear-all" onClick={clear}>Clear all filters</button></div>}
            {feed.isError?<Empty icon={<Wifi size={30}/>} title="The feed needs a moment." text={(feed.error as Error).message} action="Try again" onAction={()=>feed.refetch()}/>:feed.isPending?<div className="job-grid">{Array.from({length:6},(_,i)=><div key={i} className="skeleton-card"><div/><div/><div/></div>)}</div>:!feed.data?.jobs.length?<Empty icon={pageView==='saved'?<Bookmark size={30}/>:<Search size={30}/>} title={pageView==='saved'?'A little space for your next move.':'Let’s widen the search.'} text={pageView==='saved'?'Tap the bookmark on any role to keep it here.':incompleteCoverage?'No indexed roles match these filters. Some source feeds are incomplete or unavailable; the original portals may have matching roles.':'No indexed roles match these filters. Try a different search or explore the original sources.'} action={pageView==='saved'?'Explore roles':'Reset filters'} onAction={pageView==='saved'?()=>changeView('explore'):clear}/>:<div className={`job-grid ${layout==='list'?'list-view':''} ${feed.isFetching?'updating':''}`}>{feed.data.jobs.map(job=><JobCard key={job.id} job={job} saved={saved.includes(job.id)} onSave={()=>save(job)} onOpen={()=>openJob(job)}/>)}</div>}
            {feed.data&&feed.data.pages>1&&<div className="pagination"><span>Page {feed.data.page} of {feed.data.pages} · {feed.data.total} opportunities</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} aria-label="Previous page"><ChevronLeft size={16}/></button>{Array.from({length:Math.min(5,feed.data.pages)},(_,i)=>i+1).map(p=><button key={p} className={page===p?'current':''} onClick={()=>setPage(p)}>{p}</button>)}<button disabled={page>=feed.data.pages} onClick={()=>setPage(p=>p+1)} aria-label="Next page"><ChevronRight size={16}/></button></div></div>}
            <div className="feed-footnote"><span className="live-dot"/>Public listings. Original sources. Coverage varies.<span>Built for possibility.</span></div></section>
          </div>
        </>}
        {pageView==='sources'&&<>
          <PageHeading eyebrow="A WORLD OF OPPORTUNITY" title="Good work starts at the source." text="Company talent communities, together at last. See what’s connected and jump straight to any original portal."/>
          <div className="source-summary"><div><strong>{allSources.length}</strong><span>Company communities</span></div><div><strong>{allSources.filter(s=>s.coverage==='complete').length}</strong><span>Complete feeds</span></div><div><strong>{new Set(allSources.map(s=>s.provider)).size}</strong><span>Provider families</span></div><div><strong>{allSources.filter(s=>s.status==='blocked').length}</strong><span>Access restricted</span></div></div>
          <div className="directory-toolbar"><label><Search size={18}/><input placeholder="Find a company or provider" aria-label="Find a source" value={sourceQuery} onChange={e=>setSourceQuery(e.target.value)}/></label><select value={provider} onChange={e=>setProvider(e.target.value)} aria-label="Filter source provider"><option>All providers</option>{[...new Set(allSources.map(s=>s.provider))].sort().map(p=><option key={p}>{p}</option>)}</select></div>
          <div className="source-grid">{allSources.filter(s=>(provider==='All providers'||s.provider===provider)&&`${s.company} ${s.provider}`.toLowerCase().includes(sourceQuery.toLowerCase())).map(s=><div className="source-card" key={s.id}><div className="source-card-top"><CompanyMark id={s.id} company={s.company}/><span className={`status-badge ${STATUS[s.status]?.className}`}><span/>{s.status==='healthy'?(s.coverage==='complete'?'Complete feed':'Partial feed'):STATUS[s.status]?.label}</span></div><h2>{s.company}</h2><span className="provider-label">{s.provider} <span>·</span> {s.country}</span><p>{s.message || 'This portal is registered and awaiting its first collection.'}{s.advertisedCount!==null&&<span className="source-count-check">{s.fetchedCount ?? 0} collected / {s.advertisedCount} advertised by the feed</span>}</p><div className="source-card-footer"><div><strong>{s.jobCount}</strong> roles <span>·</span> {ago(s.lastCheckedAt)}</div><a href={s.url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${s.company} source`}><ArrowUpRight size={19}/></a></div></div>)}</div>
          {!sources.isPending&&!allSources.filter(s=>(provider==='All providers'||s.provider===provider)&&`${s.company} ${s.provider}`.toLowerCase().includes(sourceQuery.toLowerCase())).length&&<Empty icon={<Search size={30}/>} title="No communities found." text="Try another company name or provider." action="Clear source search" onAction={()=>{setSourceQuery('');setProvider('All providers');}}/>}
        </>}
        {pageView==='activity'&&<>
          <PageHeading eyebrow="YOUR ALWAYS-ON JOB RADAR" title="Fresh roles. Clear signals." text="Follow each collection run and see exactly when your sources were checked."/>
          <div className="activity-banner"><span className="activity-icon"><Radio size={26}/></span><div><h2>{stats?.scheduleEnabled?'Two-hour source checks are scheduled.':'Your job radar is ready.'}</h2><p>{stats?.nextRefreshAt?`Next scheduled window: ${localDate(stats.nextRefreshAt)}. Source checks run automatically; start times can vary.`:'View source check times below to see how current the published feed is.'}</p></div><button onClick={refreshRoles} disabled={refreshing}><RefreshCw size={16} className={refreshing?'spin':''}/> {access.data?.canRefresh?'Check now':'Reload feed'}</button></div>
          {refreshing&&access.data?.canRefresh&&<div className="progress-block"><div><strong>Checking your communities</strong><span>{refresh?.processed||0} / {refresh?.sourceCount||59}</span></div><progress max={refresh?.sourceCount||59} value={refresh?.processed||0}/><p>Existing listings stay available while new roles are collected.</p></div>}
          <div className="run-table"><div className="table-heading"><h2>Refresh history</h2><span>Latest 20 runs</span></div>{!runs.data?.length?<Empty icon={<Clock3 size={28}/>} title="Your first chapter starts here." text="Refresh roles to begin collecting. Every run will appear here with its results."/>:<div className="table-scroll"><table><thead><tr><th>Started</th><th>Outcome</th><th>Connected sources</th><th>New roles</th><th>Roles checked</th></tr></thead><tbody>{runs.data.map(r=><tr key={r.id}><td>{localDate(r.startedAt)}</td><td><span className={`status-badge ${r.status==='completed'?'healthy':r.status==='running'?'pending':'blocked'}`}><span/>{r.status==='partial'?'Partially completed':r.status[0].toUpperCase()+r.status.slice(1)}</span></td><td>{r.successCount} / {r.sourceCount}</td><td>{r.newCount}</td><td>{r.jobCount}</td></tr>)}</tbody></table></div>}</div>
          <div className="activity-explainer"><div><span>01</span><h3>Collect from the source</h3><p>Public APIs and structured listings bring in contract opportunities directly from company talent communities.</p></div><div><span>02</span><h3>Keep the feed clean</h3><p>Stable source IDs prevent duplicates. Posting dates stay separate from the time a role was discovered.</p></div><div><span>03</span><h3>Make freshness visible</h3><p>Restricted or unavailable sources keep their last successful data. Source health tells you what happened.</p></div></div>
        </>}
      </div>
    </main>
    {notice&&<div className="toast" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    {selected&&<JobDetails job={selected} saved={saved.includes(selected.id)} onSave={()=>save(selected)} onClose={closeJob}/>}
    {info&&<InfoDialog onClose={()=>setInfo(false)}/>}
  </div>;
}
function Metric({icon,value,label,sub}:{icon:ReactNode;value:number|undefined;label:string;sub:string}){return <div className="metric"><span className="metric-icon">{icon}</span><div><strong>{value===undefined?'—':value.toLocaleString()}</strong><span>{label}</span><small>{sub}</small></div></div>;}
function FilterSection({title,children}:{title:string;children:ReactNode}){return <div className="filter-section"><h3>{title}<ChevronDown size={13}/></h3>{children}</div>;}
function CheckFilter({label,checked,onChange,count}:{label:string;checked:boolean;onChange:()=>void;count?:number}){return <label className="check-filter"><input type="checkbox" checked={checked} onChange={onChange}/><span>{label}</span>{count!==undefined&&<small>{count}</small>}</label>;}
function Empty({icon,title,text,action,onAction}:{icon:ReactNode;title:string;text:string;action?:string;onAction?:()=>void}){return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p>{action&&<button onClick={onAction}>{action}<ArrowRight size={15}/></button>}</div>;}
function PageHeading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="page-heading"><div className="eyebrow"><span className="eyebrow-line"/>{eyebrow}</div><h1>{title}</h1><p>{text}</p></section>;}
function JobCard({job,saved,onSave,onOpen}:{job:Job;saved:boolean;onSave:()=>void;onOpen:()=>void}){
  const isNew=job.postedAt&&Date.now()-Date.parse(job.postedAt)<24*3_600_000;
  return <article className="job-card"><div className="job-card-top"><div className="company"><CompanyMark id={job.sourceId} company={job.company}/><div><strong>{job.company}</strong><span>{job.provider} talent community</span></div></div><button className={`save-button ${saved?'saved':''}`} aria-label={saved?`Unsave ${job.title}`:`Save ${job.title}`} aria-pressed={saved} onClick={onSave}><Bookmark size={19} fill={saved?'currentColor':'none'}/></button></div><div className="job-card-main"><h3><button onClick={onOpen}>{job.title}</button></h3><div className="job-location"><MapPin size={13}/><span>{job.location}</span></div><div className="job-tags"><span className={job.workMode==='Remote'?'tag remote':'tag'}>{job.workMode==='Remote'&&<Wifi size={11}/>} {job.workMode==='Unspecified'?'Workplace not specified':job.workMode}</span><span className="tag">Contract</span>{job.duration&&<span className="tag"><Clock3 size={11}/>{job.duration}</span>}</div></div><div className="job-card-bottom"><div><strong className={!job.payMin&&!job.payMax?'no-pay':''}>{pay(job)}</strong><span>{isNew&&<b className="new-label">NEW</b>}{job.postedAt?`Posted ${ago(job.postedAt)}`:`Discovered ${ago(job.firstSeenAt)}`}</span></div><button className="details-button" onClick={onOpen} aria-label={`View ${job.title}`}>View role<ArrowUpRight size={15}/></button></div></article>;
}
function JobDetails({job,saved,onSave,onClose}:{job:Job;saved:boolean;onSave:()=>void;onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="job-dialog" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-labelledby="job-dialog-title"><div className="dialog-top"><span>YOUR NEXT OPPORTUNITY</span><button className="icon-button" aria-label="Close role details" onClick={onClose}><X size={21}/></button></div><div className="dialog-scroll"><div className="detail-company"><CompanyMark id={job.sourceId} company={job.company} size="large"/><div><strong>{job.company}</strong><span>{job.provider} talent community</span></div><button className={`save-button ${saved?'saved':''}`} aria-label={saved?'Unsave role':'Save role'} onClick={onSave}><Bookmark size={21} fill={saved?'currentColor':'none'}/></button></div><h2 id="job-dialog-title">{job.title}</h2><div className="job-location"><MapPin size={15}/>{job.location}</div><div className="job-tags"><span className="tag">{job.workMode==='Unspecified'?'Workplace not specified':job.workMode}</span><span className="tag">Contract</span><span className="tag">{job.category}</span></div><div className="detail-facts"><div><small>COMPENSATION</small><strong>{pay(job)}</strong></div><div><small>CONTRACT LENGTH</small><strong>{job.duration || 'See original listing'}</strong></div></div><h3>About this opportunity</h3>{job.description?<p className="job-description">{job.description}</p>:<p className="job-description">Full role details are available on the original talent community. Open the listing to see requirements, responsibilities, and application instructions.</p>}{job.skills.length>0&&<><h3>Skills mentioned</h3><div className="skills">{job.skills.map(s=><span key={s}>{s}</span>)}</div></>}<div className="listing-metadata"><div><span>Posted by source</span><strong>{localDate(job.postedAt)}</strong></div><div><span>First discovered</span><strong>{localDate(job.firstSeenAt)}</strong></div><div><span>Last verified</span><strong>{localDate(job.lastSeenAt)}</strong></div></div><p className="source-disclaimer">This role is offered through a contingent talent community. Employment terms and availability are confirmed by the original provider.</p></div><div className="dialog-footer"><button className="secondary-button" onClick={onSave}><Bookmark size={16} fill={saved?'currentColor':'none'}/>{saved?'Saved to your list':'Save for later'}</button><a className="primary-button" href={job.applyUrl} target="_blank" rel="noopener noreferrer">View original & apply<ArrowUpRight size={17}/></a></div></dialog>;
}
function InfoDialog({onClose}:{onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="info-dialog" onCancel={onClose} aria-labelledby="info-title"><button className="icon-button info-close" onClick={onClose} aria-label="Close information"><X size={20}/></button><span className="info-symbol"><Compass size={32}/></span><h2 id="info-title">More opportunity.<br/>Fewer open tabs.</h2><p>Contract Atlas brings public contract listings from company talent communities into a single searchable feed.</p><ul><li><Check size={16}/>Every application opens the original listing.</li><li><Check size={16}/>“New” uses the source’s posting date.</li><li><Check size={16}/>The source directory shows collection health.</li><li><Check size={16}/>Saved roles are stored on this device.</li></ul><button className="primary-button" onClick={onClose}>Find your next chapter<ArrowRight size={16}/></button></dialog>;}
